### ISSUE TITLE
Date comparison

### ISSUE THREAD

**Issue by bserem** [dbis-uibk/relax#1]
Hello!
Thanks for the excellent project, it actually helps me understand relational algebra by writing SQL queries.

I am trying to do a date comparison, but there is always an error message coming up saying I am comparing to a number.
Dates are stored properly in my dataset, and I am trying like this `date = '2016-01-01'` with or withour quotes.
Any hints? The documentation didn't mention something about that.
Thanks

**Comment by mtschu** [comment]
Hi - dates have their own type and thus are neither numbers nor strings. Unlike in most database systems you have to do an explicit cast using the date() function:    my_date >= date('2016-01-01')
(see also https://dbis-uibk.github.io/relax/help.htm#relalg-valueexpr)
