### ISSUE TITLE
Support conversion of a subquery to an atomic value

### ISSUE THREAD

**Issue by dmgerman** [dbis-uibk/relax#10]
The following query is rejected by relax:

`select distinct * from R where R.a = (select max(a) from R);`

In this case, the challenge is for relax to discover that this query returns a single tuple and a single value (always).

**Comment by michaelrampl** [comment]
Hello,

Thank you for using Relax and making good suggestions.
Relax is designed to parse SQL in relational algebra. This process is similar to most relational database systems.
Unfortunately, this is also really complex which means introducing such functionality would only work with a tremendous development / testing effort. Additionally, Relax was designed to learn relational algebra, SQL is only a side-feature. This is why we decided to not implement this. (Related to #18 )
