### ISSUE TITLE
was ANTLR used while developing relax?

### ISSUE THREAD

**Issue by rusyasoft** [dbis-uibk/relax#109]
First of all thank you for creating such a great calculator tool for Relational Algebra

I'm just wondering, was the ANTLR or some similar tool used while developing RelaX ?

If so, could you share .g4 files for ANTLR? Or did you guys just implement everything from scratch?

I'm new in this area, so far what I have understood ANTLR is good tool for describing languages, but couldn't find full implemented Relation Algebra. If you have some information regarding to this, would be really great.

Thank you!

**Comment by immutablestate** [comment]
The parser uses PEG.js. You can find the grammar definitions in the `.pegjs` files [here](https://github.com/dbis-uibk/relax/tree/development/src/db/parser).
