### ISSUE TITLE
Add GUI for creating Dataset

### ISSUE THREAD

**Issue by jugaldb** [dbis-uibk/relax#114]
Creating a GUI for creation of dataset would be really beneficial, it would bring in a lot of new users and make it really more interactive and user friendly

Thanks

**Comment by michaelrampl** [comment]
Hello,
Thank you for using Relax.

A GUI already is in place....
You can edit data sets over the "group editor" tab

![image](https://user-images.githubusercontent.com/60225162/93577912-edea6f80-f99c-11ea-90da-33c0e66928a4.png)

You can then click on "add new relation" to open a GUI which serves a table editor

![image](https://user-images.githubusercontent.com/60225162/93578035-18d4c380-f99d-11ea-9b97-1c682b27f89f.png)
