### ISSUE TITLE
Error in Dataset 

### ISSUE THREAD

**Issue by Up2Iso** [dbis-uibk/relax#115]
There is an error in the dataset "Database Systems The Complete Book - Exercise 2.4.1": under the table "Product" the line  ('B' | 2007 | 'pc') should be ('B' | 2007 | 'laptop') as in the book. Unless I'm missing something...

**Comment by michaelrampl** [comment]
Thank you for you support!
This was indeed a typo on our end.
Fixed with 072205ca384fb3a72f357ad7cac945d1994d54cd
