### ISSUE TITLE
Update 'group by' operator for relational algebra

### ISSUE THREAD

**Issue by KesabhAT** [dbis-uibk/relax#12]
you can add some more operations like
average,count-distinct,max,min...
Other issues like 'arrow pointing towards right missing' should also be fixed
Thanks for making RelaX by the way

**Comment by KesabhAT** [comment]
you cannot execute queries like
r <- r-E[http://www.cs.sfu.ca/CourseCentral/354/zaiane/material/notes/Chapter3/node22.html](url)

**Comment by michaelrampl** [comment]
As in the new version we support MIN, MAX, AVG, SUM, COUNT and COUNT_ALL. This now seems to fulfill your feature request.

**Comment by michaelrampl** [comment]
Fixed right arrow feature request with cc514eae11132939f3925bae21477b466b0a6a7d
