### ISSUE TITLE
Set Difference does not give the correct result

### ISSUE THREAD

**Issue by ekeilty17** [dbis-uibk/relax#120]
Import the attached file into the group editor. 

[query.txt](https://github.com/dbis-uibk/relax/files/5356814/query.txt)

And then try to do R - S. It will produce the wrong result. Then if you do R (anti-join) S it will produce the correct result. When all columns from 2 relations are identical, these two operations should produce the same results. However, they do not.

**Comment by ekeilty17** [comment]
In `relax/src/db/exec/Table.ts` I believe this method is written incorrectly and is the reason for set difference not working.

```javascript
static rowEqualsRow(rowA: Tuple, rowB: Tuple) {
    if (rowA.length !== rowB.length) {
        return false;
    }

    for (let i = 0; i < rowA.length; i++) {
        let found = false;
            for (let j = 0; j < rowB.length; j++) {
                if (rowA[i] === rowB[j]) {
                    found = true;
                }
            }

            if (!found) { return false; }
        }

    return true;
}
```

This is the correct implementation I believe. However, someone should probably test it first
```javascript
static rowEqualsRow(rowA: Tuple, rowB: Tuple) {
    if (rowA.length !== rowB.length) {
        return false;
    }

    let match = true;
    for (let i = 0; i < rowA.length; i++) {
        if (rowA[i] !== rowB[i]) {
           match = false;
           break;
        }
    }
    
    return match
}
```

**Comment by r-prem** [comment]
Fixed with [454bcc](https://github.com/dbis-uibk/relax/commit/454bcc9d164abbb01f20bc550f1ba4021e907dd1)
