### ISSUE TITLE
Please add relational calculus (e.g., TRC) as a language!

### ISSUE THREAD

**Issue by dtabass** [dbis-uibk/relax#122]
The RelaX calculator ROCKS.  I use it in teaching the relational algebra to 100's of students annually at UC Irvine and having it available has proven game-changing in terms of helping students to really learn it - by doing it.  It would be terrific if it could also be extended with support for the tuple-relational calculus!  (Like it has been for SQL.)  Any chance of that happening?  That's another "theory language" where a tool like this would be game-changing.

**Comment by rlaiola** [comment]
https://github.com/dbis-uibk/relax/issues/157#issuecomment-2194600445

**Comment by rlaiola** [comment]
PR https://github.com/dbis-uibk/relax/pull/232 adds TRC support.
