### ISSUE TITLE
Missing pages when displaying relations

### ISSUE THREAD

**Issue by 0x03A9** [dbis-uibk/relax#126]
It seems that in some cases RelaX doesn't display all tuples of a relation but instead stops displaying tuples after a certain number of pages.

A minimal example where one can see this problem in action can be found [here](https://gist.github.com/0x03A9/3d5830083e34b42962b894669be68d85).

The relation **R** in this example has 21 tuples, but when loading the data into RelaX and executing the query `R` only the first 20 of them are displayed on 2 pages with 10 tuples each:

![Screenshot_2020-11-18 RelaX - relational algebra calculator](https://user-images.githubusercontent.com/58669161/99526637-cfecbb80-299b-11eb-83fb-878d6997d079.png)

**Comment by utybo** [comment]
Hello, we encountered this, here's another example (Database Systems The Complete Book - Exercise 2.4.3):

```
Ships
```

![image](https://user-images.githubusercontent.com/5175705/104015528-0af9b700-51b5-11eb-8c68-c0f531dd91a3.png) ![image](https://user-images.githubusercontent.com/5175705/104015507-0503d600-51b5-11eb-95db-63443e3153b9.png)


No Yamato ship here, however:
```
σ name = 'Yamato' Ships
```
![image](https://user-images.githubusercontent.com/5175705/104015564-19e06980-51b5-11eb-8400-d2c50386f76b.png)

Hello there!

Intuitively, I'd say this is a pagination problem 🤷

**Comment by 0x03A9** [comment]
@utybo You're right, it is a pagination problem. In fact I've already created a pull request to fix it.

**Comment by r-prem** [comment]
Fixed with [7277e17](https://github.com/dbis-uibk/relax/commit/7277e17267afb084c79f8cfb77639461ad4298cb)
Thanks @0x03A9
