### ISSUE TITLE
Cannot get the Assignment operator to work.

### ISSUE THREAD

**Issue by swen3165lecturer** [dbis-uibk/relax#132]
I have tried using both the left arrow and the assignment operator to create temporary ralations. Neither has worked, Can you help?

**Comment by r-prem** [comment]
This might help: https://dbis-uibk.github.io/relax/help#relalg-assignment
Otherwise a quick example using the UIBK - R, S, T dataset:
`A = π a, d (R ⨝ T)`
`A`
