### ISSUE TITLE
Right-join and full-outer join crash RelaX

### ISSUE THREAD

**Issue by yle-kot** [dbis-uibk/relax#133]
For the attached  dataset, the following behaviour is observed.

The following commands will crash RelaX with an error 'unknown type defined':
R1 ⟖ R2
R1 ⟗ R2

while these do not
R2 ⟗ R1
R2 ⟖ R1
R1 ⟕ R2 

Dataset:
```
group: HW4Set

R1 = {
ID:number, A:string, B:string
0, 'A0', 'B0'
1, 'A1', 'B1'
2, 'A2', 'B2'
}
R2 = {
ID:number, B:string, D:string, E:string
0, 'B0', 'D0', 'E0'
2, 'B99', 'D2', 'E2'
3, 'B3', 'D3', 'E3'
}
```

The dataset can be accessed [here]( https://dbis-uibk.github.io/relax/calc/gist/f535d694d2f9e3b2a139baee4f3abdf5)

**Comment by r-prem** [comment]
Fixed with [f25be62](https://github.com/dbis-uibk/relax/commit/f25be627b2d92db5f56603f0876977d87bbaaaa3). 
Table row width was being calculated incorrectly.
