### ISSUE TITLE
Error: i18n is not defined

### ISSUE THREAD

**Issue by 961028** [dbis-uibk/relax#134]
group: tenta 

Assignment = {
course:string, name:string, deadline:number
'TDA357', 'Lab1', 2500
'TDA357', 'Lab2', 6000
'TDA144', 'Lab2', 2000
}

Submission = {
idnr:number, student:string, course:string, assignment:string, stime:number
0, 's1', 'TDA357', 'Lab1', 1000
1, 's2', 'TDA357', 'Lab2', 2000 
2, 's1', 'TDA357', 'Lab1', 3000
3, 's3', 'TDA144', 'Lab2', 1000 
}

SubmittedFile = {
submission:number, filename:string, filesize:number
1, 'tables.sql', 1300
1, 'comment.txt', 100
2, 'views.sql', 800
2, 'tables.sql', 900
}

SELECT
	Submission.student,
	SUM(filesize) AS totalSize
FROM 
	Submission LEFT JOIN SubmittedFile 
ON 
	submission = idnr
WHERE
	COUNT(Submission.student) > 0
GROUP BY
	Submission.student

Any idea why this is happening?
BR

**Comment by r-prem** [comment]
Fixed with [82b7e57](https://github.com/dbis-uibk/relax/commit/82b7e57f87f4b915dded92d6a52dbe21195c1288). Thanks @danielSbastos
