### ISSUE TITLE
Link on User Tutorial leads to "404 This route doesn't exist"

### ISSUE THREAD

**Issue by aron-hoogeveen** [dbis-uibk/relax#136]
The links for the "bank example dataset" in the [user tutorial](https://dbis-uibk.github.io/relax/help#tutorial-user-relalg) lead to a "404 this route doesn't exist". 
The broken link: https://dbis-uibk.github.io/relax/calc.htm?data=gist:2cfb981fbc5676182d64

**Comment by r-prem** [comment]
Fixed with f187eda
