### ISSUE TITLE
Left arrow operator doesn't work

### ISSUE THREAD

**Issue by detuur** [dbis-uibk/relax#14]
When using the left arrow operator to rename columns, the built-in arrow from the toolbar doesn't seem to work, no matter how you format it.

````SQL
rho manufacturer <- maker (Product) --this works
rho manufacturer ← maker (Product) --this throws errors
````

If the left arrow operator is meant to work as the assignment operator (like in some dialects of relational algebra), that too doesn't seem to be working.

**Comment by michaelrampl** [comment]
This now works in the development version. We will update the release once the development version is stable.
