### ISSUE TITLE
Attribute order gets mixed up on right outer join

### ISSUE THREAD

**Issue by fwheinz** [dbis-uibk/relax#155]
In some cases, the order of the attributes gets mixed up on a right outer join. See this query:

pi City
({ Kdnr:number,Name:string,PC1:number
  137, John, 31337 }
right outer join PC1=PC2
{ City:string,PC2:number
  Philadelphia,31338 })

The result is:

City
-------
31338

If the projection is removed, one can see that some table columns are missing in the data, but not in the header of the table.

**Comment by r-prem** [comment]
Fixed by [f25be62](https://github.com/dbis-uibk/relax/commit/f25be627b2d92db5f56603f0876977d87bbaaaa3)
