### ISSUE TITLE
Feature request: Execution time

### ISSUE THREAD

**Issue by fwheinz** [dbis-uibk/relax#156]
It would be a nifty feature if the total time of execution (and maybe the execution time for each step in the operator tree) would be shown (e.g. in milliseconds). This depends probably on the performance of the local client machine, but it is interesting to show the performance gain, when several semantically equal queries are performed with different execution plans.

**Comment by r-prem** [comment]
The total execution time is now visible. The execution time per step in the tree is currently being worked on.
<img width="250" alt="Screenshot 2022-07-08 at 12 26 33" src="https://user-images.githubusercontent.com/92574486/177974879-9eb9a8ad-0c6b-4922-ab79-1eb0103bb477.png">

**Comment by r-prem** [comment]
Execution Time per node now available. These times will not be 100% accurate as they are rounded to the nearest ms.
