### ISSUE TITLE
Show some examples

### ISSUE THREAD

**Issue by lancejpollard** [dbis-uibk/relax#160]
It would be nice if you had some examples, I can't seem to find anything and I've tried for about 20 minutes and haven't produced any results :) Seems like a cool project though!

**Comment by LukeLR** [comment]
The main page as well as the help sections contain examples and a step-by-step introduction as well as a reference for both relational algebra and SQL. Did you check them out?

**Comment by lancejpollard** [comment]
I guess I missed them, I will scour around some more.
