### ISSUE TITLE
Site crashes on a particular query

### ISSUE THREAD

**Issue by vibhav011** [dbis-uibk/relax#161]
I am using the **Silberschatz - UniversityDB** database and wrote the following relational algebra query: `department ⟖ (instructor ⟕ section)`. This caused the site getting crashed with two error messages on the console:
<img width="597" alt="Screenshot 2022-01-25 at 3 29 34 AM" src="https://user-images.githubusercontent.com/55905634/150872103-74dba5a7-e6ac-4713-b17f-d3c26001666f.png">

Please look into this.

**Comment by r-prem** [comment]
Fixed with [f25be62](https://github.com/dbis-uibk/relax/commit/f25be627b2d92db5f56603f0876977d87bbaaaa3). 
Table row width was being calculated incorrectly.
