### ISSUE TITLE
Adding Aggregate Functions in Relational Algebra

### ISSUE THREAD

**Issue by sifislaz** [dbis-uibk/relax#162]
First of all, thanks for this very useful tool.
My suggestion is to add the feature of using aggregate functions in relational algebra mode, because a variety of queries depends on these functions (If they are already implemented, I would appreciate to comment the way of using them).

**Comment by WormChickenWizard** [comment]
Also need this. Unfortunately it looks it isn't being maintained since the last commit was 17 months ago.

**Comment by r-prem** [comment]
It already allows the use of aggregate functions. 
The documentation can be found here: https://dbis-uibk.github.io/relax/help#relalg-operations-orderby
If you scroll down you can see which functions are supported.
