### ISSUE TITLE
Website crashes under certain condition

### ISSUE THREAD

**Issue by BenjaminMichaelis** [dbis-uibk/relax#167]
Under certain query, when clicking on the relational tree, the site just goes blank and requires a reload.

![tempppppp](https://user-images.githubusercontent.com/22186029/155275563-4f6a32ab-e9e7-42aa-b0de-1a6e1af06a39.gif)

**Comment by r-prem** [comment]
@BenjaminMichaelis Can you provide the gist / dataset in which this is occurring?

**Comment by BenjaminMichaelis** [comment]
I have looked around a bit and will look more, but used many gists around this time and am not sure exactly which one I used to cause this problem...

**Comment by r-prem** [comment]
Alright, I'm closing the issue as I cannot reproduce it.
