### ISSUE TITLE
Why DISTINCT is by default?

### ISSUE THREAD

**Issue by samnklcf** [dbis-uibk/relax#171]

**Comment by rprem1** [comment]
If you mean in relational algebra, it is because the projection operator will always return distinct tuples. You can read more about it here: https://en.wikipedia.org/wiki/Projection_(relational_algebra)

**Comment by r-prem** [comment]
If you mean in relational algebra, it is because the projection operator will always return distinct tuples. You can read more about it here: https://en.wikipedia.org/wiki/Projection_(relational_algebra)
