### ISSUE TITLE
CSV upload does not work(?)

### ISSUE THREAD

**Issue by flyingbeat** [dbis-uibk/relax#173]
Hi, first of all, great project!
I'm not sure if I am doing it wrong but I would like to create a dataset from the Mondial database. I attached a sample CSV table below. I'm not sure what I'm doing wrong here. I selected create new dataset > add new relation > upload from CSV. After clicking OK I get a type error in the console. 

Thanks!

[country.csv](https://github.com/dbis-uibk/relax/files/8824471/country.csv)

**Comment by r-prem** [comment]
The issue should now be resolved.
