### ISSUE TITLE
Couple of Missing Clauses and Subqueries ❗️

### ISSUE THREAD

**Issue by danbugs** [dbis-uibk/relax#18]
Hello!

First of all, fantastic product! Great tool to easily see the relational algebra equivalent of SQL code.

The only downsides I noticed were:

1. It doesn't seem to understand the `IN` or `EXISTS` clause.
1. I'm not sure it understands subqueries.

Do you plan on implementing this? Let me know if I can help in any way!

Cheers!

**Comment by michaelrampl** [comment]
Hello,

Thank you for using Relax and making good suggestions. 
Relax is designed to parse SQL in relational algebra. This process is similar to most relational database systems.
Unfortunately, this is also really complex which means introducing such functionality would only work with a tremendous development / testing effort. Additionally, Relax was designed to learn relational algebra, SQL is only a side-feature. This is why we decided to not implement this.
