### ISSUE TITLE
Positional notation

### ISSUE THREAD

**Issue by Lumix26** [dbis-uibk/relax#182]
Hi! magnificent application!
i'm wondering if it is possible to use the positional notion (ex $1 to reference first attribute) ?

**Comment by rlaiola** [comment]
> Hi! magnificent application! i'm wondering if it is possible to use the positional notion (ex $1 to reference first attribute) ?

This feature is described here: https://dbis-uibk.github.io/relax/help#tutorial-user-relations

Example:
```
π [1], [3] ( R )
```

**Note:** To run the test refer to http://dbis-uibk.github.io/relax/calc/local/uibk/local/0

**Comment by evazangerle** [comment]
This issue was closed due to inactivity.
