### ISSUE TITLE
Renaming multiple columns - disambiguation in self joins

### ISSUE THREAD

**Issue by brownidj** [dbis-uibk/relax#188]
I haven't been able to get the syntax correct - could someone please provide a simple example

Many thanks

**Comment by rlaiola** [comment]
> I haven't been able to get the syntax correct - could someone please provide a simple example
> 
> Many thanks

@brownidj, do you mean something like this?

R x rho r (R)

Just try it using this URL: http://dbis-uibk.github.io/relax/calc/local/uibk/local/0

**Comment by evazangerle** [comment]
This issue was closed due to inactivity.
