### ISSUE TITLE
Necesito ayuda urgente

### ISSUE THREAD

**Issue by monteero13** [dbis-uibk/relax#190]
Intento poner mi base de datos a traves de este enlace y no me deja https://gist.github.com/monteero13/219eb7450e2883d7bbab879511145444
Ayuda por favor

**Comment by rlaiola** [comment]
> Intento poner mi base de datos a traves de este enlace y no me deja https://gist.github.com/monteero13/219eb7450e2883d7bbab879511145444 Ayuda por favor

Check the guidelines on how to create a dataset: https://dbis-uibk.github.io/relax/help#tutorial-maintainer-create-dataset

Cheers!

**Comment by evazangerle** [comment]
This issue was closed due to inactivity.
