### ISSUE TITLE
Can RelaX due with the multiline statements?

### ISSUE THREAD

**Issue by tdnghia1977** [dbis-uibk/relax#192]
I write an multiline statement like below:
pc1 = (π nhanvien.manv, ho, tenlot, ten, mada (nhanvien ⨝ nhanvien.manv=phancong.manv (phancong))) pc1 
π pc1.manv, ho, tenlot, ten, dean.tenda (pc1 ⨝ pc1.mada=dean.mada (dean))
Can RelaX due with kind of statements?
Thanks a lot!

**Comment by rlaiola** [comment]
@tdnghia1977 could you provide the database gist?

**Comment by evazangerle** [comment]
This issue was closed due to inactivity.
