### ISSUE TITLE
Crahses for no reason

### ISSUE THREAD

**Issue by SoroushVahidi** [dbis-uibk/relax#199]
Give the table below to it as the input:

-- this is an example
group: CS 631 Assignment 3

Hotel = { hotelno:number, name:string, city:string, state:string, address:string, zipcode:number, star:number
1,'Robert Treat Hotel','Newark','NJ','50 Park Pl',07102,3
2,'GITC','Newark','NJ','123 Central Ave',07102,2
3,'Kupfrian','Newark','NJ','100 Summit St',07103,1
4,'White House','Washington','DC','1600 Pennsylvania Ave',37188,5
5,'The Tardis','Jersey City','NJ','Washburn St',07306,5
}

Guest = { guestno:number, name:string, city:string, address:string, zipcode:number
1,'John Parker','Washington','1600 Pennsylvania ave',37188
2,'River Song','Jersey City','Washburn Street',07306
3,'Alfred Simpson','Jersey City','Washburn Street',07306
4,'John Smith','Newark','123 Ferry Street',07103
5,'Bruce Wayne','Gotham','1007 Mountain Drive',10010
6,'Clark Kent','Metropolis','344 Clinton Street',33866
7,'Peter Parker','Queens','Queens Blvd',11106
}

Room = { roomno:number, hotelno:number, type:string, price:number
1,1,'2 Queen Beds',499
2,1,'1 King Bed',258
3,1,'2 Queen Beds',157
4,1,'2 Queen Beds',307
5,1,'Villa 2 Bedroom',322
6,1,'Deluxe Suite',234
7,1,'2 Queen Beds',182
8,1,'Junior Suite',475
9,1,'1 King Bed',195
10,1,'1 King Bed',474
11,1,'Deluxe Suite',478
12,1,'Deluxe Suite',275
13,1,'2 Queen Beds',269
14,1,'Villa 1 Bedroom',137
15,1,'Villa 2 Bedroom',123
16,1,'Villa 2 Bedroom',271
17,1,'Villa 2 Bedroom',493
18,1,'Deluxe Suite',344
19,1,'2 Queen Beds',305
20,1,'Deluxe Suite',251
21,1,'Villa 1 Bedroom',243
22,1,'Villa 2 Bedroom',118
23,1,'Junior Suite',487
24,1,'1 King Bed',489
25,1,'Villa 1 Bedroom',159
26,1,'1 King Bed',500
27,1,'Villa 2 Bedroom',352
28,1,'Deluxe Suite',251
29,1,'Villa 2 Bedroom',198
30,1,'2 Queen Beds',279
1,2,'1 King Bed',139
2,2,'Deluxe Suite',387
3,2,'Deluxe Suite',409
4,2,'2 Queen Beds',255
5,2,'Deluxe Suite',214
6,2,'Junior Suite',398
7,2,'Villa 2 Bedroom',234
8,2,'Villa 1 Bedroom',475
9,2,'2 Queen Beds',396
10,2,'Deluxe Suite',269
11,2,'1 King Bed',209
12,2,'Deluxe Suite',380
13,2,'Villa 1 Bedroom',353
14,2,'Deluxe Suite',286
15,2,'1 King Bed',271
1,3,'Villa 2 Bedroom',300
2,3,'1 King Bed',271
3,3,'2 Queen Beds',338
4,3,'Villa 2 Bedroom',451
5,3,'Villa 1 Bedroom',400
6,3,'Junior Suite',347
7,3,'Deluxe Suite',416
8,3,'Junior Suite',111
9,3,'1 King Bed',118
10,3,'1 King Bed',66
11,3,'Villa 2 Bedroom',492
12,3,'Junior Suite',142
13,3,'Junior Suite',170
14,3,'Junior Suite',437
15,3,'Junior Suite',486
16,3,'1 King Bed',243
17,3,'1 King Bed',230
18,3,'Junior Suite',449
19,3,'2 Queen Beds',216
20,3,'Junior Suite',107
21,3,'1 King Bed',428
22,3,'1 King Bed',144
23,3,'2 Queen Beds',387
24,3,'Deluxe Suite',100
25,3,'Villa 1 Bedroom',332
1,4,'2 Queen Beds',105
2,4,'Junior Suite',409
3,4,'Villa 2 Bedroom',254
4,4,'Villa 2 Bedroom',216
5,4,'Junior Suite',413
6,4,'Villa 1 Bedroom',123
7,4,'Villa 2 Bedroom',390
8,4,'Villa 1 Bedroom',154
9,4,'Junior Suite',222
10,4,'Villa 2 Bedroom',119
11,4,'Villa 1 Bedroom',387
12,4,'2 Queen Beds',452
13,4,'Villa 2 Bedroom',429
14,4,'1 King Bed',285
15,4,'Villa 1 Bedroom',384
16,4,'Junior Suite',307
17,4,'Junior Suite',459
18,4,'1 King Bed',194
19,4,'Deluxe Suite',353
20,4,'Villa 1 Bedroom',200
21,4,'Junior Suite',359
22,4,'Villa 1 Bedroom',371
23,4,'2 Queen Beds',97
24,4,'2 Queen Beds',134
25,4,'Villa 2 Bedroom',180
26,4,'Villa 2 Bedroom',191
27,4,'2 Queen Beds',440
28,4,'Villa 1 Bedroom',286
29,4,'1 King Bed',208
30,4,'Villa 2 Bedroom',460
31,4,'Deluxe Suite',373
32,4,'Villa 1 Bedroom',70
33,4,'2 Queen Beds',420
34,4,'Deluxe Suite',128
35,4,'Villa 2 Bedroom',277
36,4,'Villa 1 Bedroom',221
37,4,'Junior Suite',346
38,4,'1 King Bed',487
39,4,'1 King Bed',113
40,4,'Junior Suite',143
41,4,'Junior Suite',352
42,4,'Deluxe Suite',87
43,4,'Junior Suite',423
44,4,'1 King Bed',496
45,4,'Villa 2 Bedroom',125
46,4,'Villa 1 Bedroom',61
47,4,'2 Queen Beds',497
48,4,'1 King Bed',370
49,4,'Junior Suite',380
50,4,'Villa 2 Bedroom',84
51,4,'Junior Suite',281
52,4,'1 King Bed',476
53,4,'Deluxe Suite',342
54,4,'Junior Suite',242
55,4,'Junior Suite',116
56,4,'Villa 1 Bedroom',481
57,4,'Villa 2 Bedroom',250
58,4,'1 King Bed',141
59,4,'1 King Bed',169
60,4,'Villa 2 Bedroom',316
61,4,'2 Queen Beds',440
62,4,'2 Queen Beds',325
63,4,'Junior Suite',62
64,4,'1 King Bed',104
65,4,'Villa 1 Bedroom',241
66,4,'Villa 2 Bedroom',72
67,4,'Deluxe Suite',279
1,5,'Junior Suite',383
2,5,'2 Queen Beds',106
}

Booking = { hotelno:number, guestno:number, datefrom:date, dateto:date, roomno:number
1,1,2021-06-18,2021-07-16,10
1,1,2018-09-19,2018-10-05,29
1,1,2024-08-24,2024-09-22,20
2,1,2024-11-28,2024-12-15,7
1,1,2024-02-10,2024-02-28,17
1,5,2024-02-13,2024-02-28,10
1,6,2024-02-21,2024-02-28,24
2,3,2024-01-01,2024-12-31,8
1,1,2020-01-01,2020-01-16,30
1,7,2020-01-05,2020-01-07,11
5,2,2025-04-17,2025-05-05,2
5,2,2019-02-05,2019-02-20,1
5,2,2021-05-22,2021-06-18,1
5,2,2019-02-03,2019-02-20,2
5,2,2019-12-28,2020-01-26,2
1,7,2021-06-13,2021-06-20,11
2,7,2021-10-20,2021-11-11,7
3,7,2023-05-08,2023-05-15,12
4,7,2019-12-25,2020-01-10,50
3,7,2021-07-28,2021-08-10,12
5,7,2021-01-28,2021-02-10,2
}

Then run the query below:

r1=(Booking) ⨝ Booking.hotelno=Hotel.hotelno (Hotel)
π guestno (σ city='Newark' and datefrom <date('23/02/2024') and dateto>date('23/02/2024')(r1))

The website will crash.

**Comment by adruzenko03** [comment]
This is an overly verbose example, however I had the same issue. Using `σdate('23/02/2024')=date('23/02/2024')(R)` on the base DB is enough to kill it. Looking at the console, the issue is caused by using the incorrect date format `σdate('2024-02-23')=date('2024-02-23')(R)` works. That being said, the fact that the program crashes instead of throwing an error is a separate issue that requires fixing.

**Comment by rlaiola** [comment]
PR https://github.com/dbis-uibk/relax/pull/201 should fix this issue.

**Comment by evazangerle** [comment]
Thank you to @rlaiola for the fix (#201).
