### ISSUE TITLE
Translation in Spanish?

### ISSUE THREAD

**Issue by Nifled** [dbis-uibk/relax#2]
This is an awesome tool and it's used in my university (computer science) based in Mexico, I'd like to contribute with a Spanish translation for now and maybe any new features that can be added.

I've never worked with `i18next` to be honest, but I'd like to know what the process would be to do the translation. I see the `json` file under `/locales/`, but I'm not sure if that's all I'd have to do.

**Comment by ragtime** [comment]
Hi, sounds great.

If you could provide a translated version of the `locales/en/translation.json`-file i would do the rest of the integration. 
You can omit all keys where the english version is also valid in spanish (as I did with the german file `locales/de/translation.json`)

Only few features of `i18next` are actually used. It boils down to keeping the `__variableName__` placeholders.
