### ISSUE TITLE
couldn't load my data

### ISSUE THREAD

**Issue by Hemanth-Lee** [dbis-uibk/relax#200]

**Comment by trashyms** [comment]
impossible to load any dataset I tried
error message: gist not found

**Comment by rlaiola** [comment]
> impossible to load any dataset I tried error message: gist not found

Could you provide the gist url?

**Comment by trashyms** [comment]
here the gist url 
https://gist.github.com/trashyms/cd50916331af0a7ba8477ac25304a43c

It is the country example database from  MySQL.

Since I did not found in the provided I tryed to add it.

**Comment by rlaiola** [comment]
> here the gist url https://gist.github.com/trashyms/cd50916331af0a7ba8477ac25304a43c
> 
> It is the country example database from MySQL.
> 
> Since I did not found in the provided I tryed to add it.

Datasets must have a specific format. Check this out: https://dbis-uibk.github.io/relax/help#tutorial-maintainer-create-dataset

**Comment by trashyms** [comment]
I will try to generate the files according to that.
Thank you for this information.

**Comment by evazangerle** [comment]
This issue was closed due to inactivity.
