### ISSUE TITLE
Division result is not expected

### ISSUE THREAD

**Issue by medifle** [dbis-uibk/relax#22]
Test case:

gist ID: 0c3296418a9053b5132034885511e4d9

Relational Algebra
```
(π SID, CID (Grade)) ÷ (π SID (Student))
```

The expected result should be:
```
Grade.CID
---
CS305
```
but the actual result is empty

Not sure if my understanding is correct

------

The interesting thing is, it works for another working example:
```
(π SID, CID (Grade)) ÷ (π CID (Course))
```
The expected and actual result is 
```
Grade.SID
---
1000
```

**Comment by michaelrampl** [comment]
We are using `(R % S) := (pi r'(R)) -  pi r'( ( (pi r'(R)) x (S) ) - (R) )` to calculate the Devision.

When using this formula, I was able to find an issue within the subtraction.
![image](https://user-images.githubusercontent.com/60225162/82763874-0d1c2a80-9e0b-11ea-93a6-1d17f32c422b.png)

**Comment by michaelrampl** [comment]
Fixed row equality check for subtraction with 3b587f161e7bd6bf604a19a7240128adc9cb676f
