### ISSUE TITLE
Support for + operator (Extended Relational Algebra)

### ISSUE THREAD

**Issue by lcmarquez2005** [dbis-uibk/relax#223]
### The ability to sum two columns and given a column result, like relational algebra.

**Example:**
Π atribute1, atribute2, (atribute1 + atribute2 → sum_atributes) (table)
**Another Example:**
Π table1.atribute1, table2.atribute1, (table1.atribute1 + table2.atribute2 → sum_atributes) (table1 ⨝ table2)

**Comment by rlaiola** [comment]
This featured is already available. Here is an example using the [UIBK - R, S, T](https://dbis-uibk.github.io/relax/calc/local/uibk/local/0) database:

```sql
π a+d->sum (R ⨯ T)
```

**Comment by lcmarquez2005** [comment]
Oh yeah, thank you so much, great project btw!!, i liked it
