### ISSUE TITLE
Missing structure, invalid variable names

### ISSUE THREAD

**Issue by ldubravica** [dbis-uibk/relax#27]
![image](https://user-images.githubusercontent.com/17551410/60369523-37dfe200-99f4-11e9-8f73-d066fc2a9d07.png)

I think variables and structure somehow fell apart :/

**Comment by dbis-uibk-adm** [comment]
Thanks for your report!

I can't reproduce the behavior. Did you use the version hosted on [github pages](https://dbis-uibk.github.io/relax/calc.htm) or do you run locally? Which browser (version) do you use and are there active content blockers?

**Comment by ldubravica** [comment]
I run version hosted on github pages. Chrome version 76.0.... on Windows 10. Everything should be the latest. Ad blocker is turned off.

Same error still happens 2 months later and yet about 4-5 months ago, I used to use it normally on this very computer, with this setup.

**Comment by michaelrampl** [comment]
Will most likely be fixed with #49
