### ISSUE TITLE
Execute parts of query

### ISSUE THREAD

**Issue by evazangerle** [dbis-uibk/relax#43]
For developing, analysing and debugging queries, it would be quite convenient to be able to mark parts of a query (e.g., a subquery) and execute only this marked part.

**Comment by michaelrampl** [comment]
Both the Relational Algebra Editor and the SQL Editor already include this Feature
![image](https://user-images.githubusercontent.com/60225162/79418745-ab6bd380-7fb5-11ea-9a27-f25210d51b5c.png)
