### ISSUE TITLE
Add sample queries to gist

### ISSUE THREAD

**Issue by evazangerle** [dbis-uibk/relax#44]
For newbies, adding one or multiple example queries to the underlying gist and showing/adding these example queries to the query input field might help getting started (as only the execute query-button needs to be clicked to run a first query).

**Comment by r-prem** [comment]
Has been implemented in v0.28
Usage can be seen either in the readme or by looking at this gist: https://gist.github.com/r-prem/7d624a5f80dec980493f6dfd7bc1837d
