### ISSUE TITLE
Export query to file

### ISSUE THREAD

**Issue by evazangerle** [dbis-uibk/relax#45]
For submitting solutions e.g., to teachers, a standardized export (e.g., to a file) would be convienient. This could be a simple text-file holding either the greek symbols or the symbol names (pi, sigma). I'd prefer to user symbol names due to possible encoding problems.

**Comment by michaelrampl** [comment]
related to #50

**Comment by evazangerle** [comment]
duplicate of #50 ?

**Comment by michaelrampl** [comment]
Yes its a duplicate if #50
