### ISSUE TITLE
Show cardinalities in execution plan

### ISSUE THREAD

**Issue by evazangerle** [dbis-uibk/relax#47]
In the current version, cardinalities (sizes of intermediary results) are only shown when hovering the mouse over a specific node. To get a better overview of the sizes of the intermediary results, I'd rather display the cardinality of any given node within the node (e.g., below the operator in smaller font).

**Comment by michaelrampl** [comment]
Introduced result count with eb8a66751a97701a1514813cc2cc034cba60d371
![image](https://user-images.githubusercontent.com/60225162/82544800-f26d5b80-9b55-11ea-9a55-a83c15feea3a.png).
Please reopen if solution does not meet expectations.
