### ISSUE TITLE
Make results downloadable

### ISSUE THREAD

**Issue by michaelrampl** [dbis-uibk/relax#50]
Introduce functionality to download results as

- Image

- Latex

**Comment by michaelrampl** [comment]
An additional module should be implemented parsing the existing relation algebra tree structure creating the output. For image generation, a canvas should be drawn (with e.g. an easy to use 2d lib like https://konvajs.org/). A messy alternative for creating an image output could to do some sort of "screenshots" of the body containing the html tree form but this would be resolution depended and not flexible as well as perhaps buggy on some clients. For latex image generation, TikZ can be used https://texample.net/tikz/examples/tree/

**Comment by r-prem** [comment]
Results now downloadable as CSV and JPG using [html2canvas ](https://www.npmjs.com/package/html2canvas) from commit [db23746](https://github.com/dbis-uibk/relax/commit/db23746d7d77ad2a33379039cf8ab07cd389fd85)
