### ISSUE TITLE
ERROR with project / select

### ISSUE THREAD

**Issue by OmarDawoud** [dbis-uibk/relax#6]
I used this program for an assignment and for practice.
Now i am using it again, with the same exact codes i had before, and the outputs are different now.
Please fix it!

**Comment by ragtime** [comment]
Hi. 
Can you provide an example query to replicate your issue?

**Comment by hex-m** [comment]
@OmarDawoud: Thank you! Feedback is very much appreciated. Please try to be as precise as possible. That helps the developers to find and fix problems fast.

Simon Tatham wrote a nice [article](https://www.chiark.greenend.org.uk/~sgtatham/bugs.html) about how to write efficient bug reports. You may find that helpful.
