### ISSUE TITLE
anti-join bug

### ISSUE THREAD

**Issue by Sebastian-Nielsen** [dbis-uibk/relax#67]
Code:
		(π P.code, P.name, P.size, S.name, S.location, S.phone (S ⨯ E ⨯ P))  
		▷ 
		(π P.code, P.name, P.size, S.name, S.location, S.phone (S ⨯ E ⨯ P))		

Dataset:
group: UIBK - R, S, T
description: Tables from and for the lecture [Databases: Foundations, Data Models and System Concepts - University of Innsbruck](http://dbis-informatik.uibk.ac.at/249-0-VO-Datenbanksysteme.html) chapter 3 

PIZZA = {
code, name, size
0, 'magaritta', 10
1, 'magaritta', 12
2, 'salat og kebab', 12
3, 'khaans', 12
4, 'ananas', 8
13, 'cursed pizza', 69
}

STORE = {
name, location, phone

'khans pizza', 'Vejle', 1111
'Sunshine', 'Randers', 2222
'Pizza cafe', 'Aarhus', 3333
'Forladt shop', 'Aarhus', 3333
}

SELLS = {
store_name, code, price

'khans pizza', 3, 90
'khans pizza', 1, 65
'Sunshine', 1, 84
'Sunshine', 2, 10
'Sunshine', 4, 70
'Pizza cafe', 1, 60
'Pizza cafe', 2, 40
'Pizza cafe', 4, 45
}

**Comment by Sebastian-Nielsen** [comment]
Expected result is non tuples being returned as anything anti-joined with itself should return nothing. However, the result of executing the code is equal to table of either of the two tables in the anti-join

**Comment by michaelrampl** [comment]
Not reproducible with `(STORE ⨯ SELLS) ▷ (STORE ⨯ SELLS)` but with `(PIZZA ⨯ SELLS) ▷ (PIZZA ⨯ SELLS)`.
Additionally, everything works as expected when using joins instead of cross joins e.g.
`(SELLS join STORE join PIZZA) ▷ (SELLS join STORE join PIZZA)` or `(PIZZA join SELLS) ▷ (SELLS)`

**Comment by michaelrampl** [comment]
fixed with 116319223c65465a698611aa5b6775d70e9a955d d83a5272b3a4a5b472f02dd0ea38909f2cfb66ac d077c2468881d7def299d9fc84a5812f4155ebbd
