### ISSUE TITLE
GitHub Pages Down

### ISSUE THREAD

**Issue by ZachAttackMLR** [dbis-uibk/relax#69]
Not sure if a migration is currently being performed since the site can also be found at [http://138.232.66.66/ra/](http://138.232.66.66/ra/), but I figured if this was unintentional, it'd be worth pointing out that [this](https://dbis-uibk.github.io/relax/) link now results in a 404.

**Comment by michaelrampl** [comment]
Thank you for your attention!
We are currently migrating our deployment, please stay patient
