### ISSUE TITLE
[Test] Top menu doesn't work

### ISSUE THREAD

**Issue by immutablestate** [dbis-uibk/relax#70]
The top menu in the test version (the one that says "Calculator", "Sprache", "Feedback", "Hilfe (en)") doesn't work correctly. Clicking "Calculator" or selecting a different language with "Sprach" leads to a 404 error.

The same happens when clicking on "Feedback" and then using the browser's back button.

**Comment by michaelrampl** [comment]
fixed with 3a420fb
