### ISSUE TITLE
[Test] Size of dataset overlay

### ISSUE THREAD

**Issue by evazangerle** [dbis-uibk/relax#79]
The overlay when selecting/loading/creating a new dataset is too large (Chrome 80.0.3987.163 on Fedora 31), the close button is cut off.

![image](https://user-images.githubusercontent.com/10127753/79194184-6bc5b000-7e2c-11ea-8d85-8faa457f877e.png)

**Comment by michaelrampl** [comment]
fixed with 9edf259b805bff910f3163df19df5c199a006cbd
