### ISSUE TITLE
Add a list of recently used gists

### ISSUE THREAD

**Issue by mcnuttandrew** [dbis-uibk/relax#8]
While the process of uploading data through gists is quite smooth, it can be a pain to need to re-enter gist id again and again. This might come up if you are switching between gists frequently or accidentally close the page. To address this, I propose maintaining a list of recently used gists in localstorage and populating either a dropdown or straight list just below the "load dataset stored in gist" section of the data selection tab.

Thanks for making such a great project, it's very fun.

**Comment by ragtime** [comment]
Hi
Having a personal history of recently used gist-ids is a great idea. thx

If you just want to open/share a specific gist you could use a link like `https://dbis-uibk.github.io/relax/?data=gist:2cfb981fbc5676182d64`. 
But it's planned to make this process smother in the future.

More information about the links could be found at https://dbis-uibk.github.io/relax/help.htm#tutorial-maintainer-share-dataset
