### ISSUE TITLE
[Test] Link to maintainer tutorial is broken

### ISSUE THREAD

**Issue by evazangerle** [dbis-uibk/relax#80]
The link https://michaelrampl.github.io/help#tutorial-maintainer is broken (cf. overlay for creating/selecting/... a datsaet).

**Comment by michaelrampl** [comment]
fixed with 26687295a58526a5ea766aa4c9f2f86ef2ca4143

**Comment by michaelrampl** [comment]
fixed with 26687295a58526a5ea766aa4c9f2f86ef2ca4143
