### ISSUE TITLE
[Test] Layout query results

### ISSUE THREAD

**Issue by evazangerle** [dbis-uibk/relax#82]
Please add some padding to the results display: between the tree and the results table (or rather, the tree and the heading containing the query, followed by the results table).
![image](https://user-images.githubusercontent.com/10127753/79197419-f6f57480-7e31-11ea-8769-88d0079cc5eb.png)

**Comment by michaelrampl** [comment]
fixed with 359ad70a4bccd8047353a3ae3f81411a95cb94ad
