### ISSUE TITLE
[Test] Query results: query format

### ISSUE THREAD

**Issue by evazangerle** [dbis-uibk/relax#83]
In the results of a given query, we repeat the issued query that was posed. However, the format of the query in the results section has some formatting issues - confusing opening and closing brackets. 

![image](https://user-images.githubusercontent.com/10127753/79197746-9581d580-7e32-11ea-85b8-5ae320bf8993.png)

E.g., on https://michaelrampl.github.io/relax/calc/gist/98e1f0d0710f119c3fcb1113371ae885 issue the query (sigma A < 2 S) join (pi B,C (sigma B < 10 R))

**Comment by michaelrampl** [comment]
Fixed with eb70adaefdb7dd2fda0fee0ffdc7653cd1a4c2f9
