### ISSUE TITLE
[Test] Multi-line comment closing ignored for highlighting

### ISSUE THREAD

**Issue by evazangerle** [dbis-uibk/relax#84]
When utilizing a multi-line comment, the syntax highlighting ignores the end of the comment - i.e., the query itself should not be in "comment color". Executing this query works perfectly fine, it's only the code highlighting. 

![image](https://user-images.githubusercontent.com/10127753/79198044-1e990c80-7e33-11ea-98b0-680f0beea4d7.png)

**Comment by evazangerle** [comment]
edit: this also holds for any statement in line 2 - also formatted as comment

**Comment by michaelrampl** [comment]
fixed with c3c6a7cae434bd55deb1403a9af12248759525ca
