### ISSUE TITLE
[Test] Referencing schema in error message 

### ISSUE THREAD

**Issue by evazangerle** [dbis-uibk/relax#86]
When referring to a schema that does not exist in the current group/dataset, the error message does not correctly reflect the situation: 
- there is some parsing error
- it's not a column that cannot be found, but a table (in this case, T is not present in gist 98e1f0d0710f119c3fcb1113371ae885).

![image](https://user-images.githubusercontent.com/10127753/79198965-8d2a9a00-7e34-11ea-819f-2758da742bff.png)

**Comment by evazangerle** [comment]
nb: in the error message when hovering over the error symbol in line 1, the error message is correct. Shouldn't this be the same error message?

**Comment by michaelrampl** [comment]
probably fixed with c3c6a7cae434bd55deb1403a9af12248759525ca
