### ISSUE TITLE
[Test] Symbols in error messages

### ISSUE THREAD

**Issue by evazangerle** [dbis-uibk/relax#88]
Symbols are not shown in error messages (neither hovering over the error symbol, nor at the bottom of the query field): 
![image](https://user-images.githubusercontent.com/10127753/79200152-4c338500-7e36-11ea-8df6-bef4dd49a624.png)

**Comment by michaelrampl** [comment]
probably fixed with c3c6a7cae434bd55deb1403a9af12248759525ca
