### ISSUE TITLE
Might anyone be able to determine why my basic query is not running?

### ISSUE THREAD

**Issue by michaelsalerno** [dbis-uibk/relax#9]
My query is: σ City="NY"(Collection)

Here is my code on GitHub so you can load this into the Relational Algebra calculator: 

https://gist.github.com/mikesmithblog/5fb170c98476d3ec1b02c99e1e7020b6

**Comment by ragtime** [comment]
unfortunately the error message is not really useful in this case.

The Problem is that you use " (double quotes) instead of ' (single quotes)

so the query should look like this `σ City='NY' (Collection)`
