### ISSUE TITLE
[Test] The landing page margine problems and tables not responsive

### ISSUE THREAD

**Issue by mikevo-uibk** [dbis-uibk/relax#96]
E.g. the Logos stick together and some tables are to wide to fit on the screen on a mobile phone.

**Comment by mikevo-uibk** [comment]
![Screenshot_20200414-112603~2](https://user-images.githubusercontent.com/40760644/79220339-17362b00-7e54-11ea-82eb-15eae857409d.png)

**Comment by michaelrampl** [comment]
fixed with efb537aae6ea51bedde94a469e665281cf9f3fe7
