### ISSUE TITLE
[Test] Missleading when selection a dataset

### ISSUE THREAD

**Issue by mikevo-uibk** [dbis-uibk/relax#97]
When selection a dataset on mobile is it necessary to click the load button?

This button is "hidden" as it does not fit the screen when opening the dropdown menue.

This is related to #93

**Comment by mikevo-uibk** [comment]
![Screenshot_20200414-112508~2](https://user-images.githubusercontent.com/40760644/79220301-08e80f00-7e54-11ea-8903-7a2c9a817441.png)

**Comment by frodito** [comment]
AFAIK, the dataset is loaded when clicking on one of the datasets. For me the missleading thing was, that the popup is not closed automatically.

**Comment by michaelrampl** [comment]
introduced auto modal close and other improvements with 1c68fc7aa86bb8fbef458d588cd8ff388e0c008a
